# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Ian
tagline:          'A site about me'
description:      'A site for Ian Lafferty using the Hyde Jekyll theme'
url:              http://hyde.getpoole.com
baseurl:          https://ianjlafferty.github.io./

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
